<a href="https://colab.research.google.com/github/LucasA0911/Analise_de_dados/blob/main/aula_modulo4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Começando com a biblioteca Pandas

## Importação da biblioteca

In [1]:
# Importanto a biblioteca
import pandas as pd

## Gerando dados para manipular com o pandas

In [2]:
dados = {
    'coluna-1': [1,2,3,4,5],
    'coluna-2': ['a','b','c','d','e'],
    'coluna-3': [1.1,2.2,3.3,4.4,5.5]
}

In [4]:
dados

{'coluna-1': [1, 2, 3, 4, 5],
 'coluna-2': ['a', 'b', 'c', 'd', 'e'],
 'coluna-3': [1.1, 2.2, 3.3, 4.4, 5.5]}

In [5]:
df = pd.DataFrame(dados)

In [6]:
df

   coluna-1 coluna-2  coluna-3
0         1        a       1.1
1         2        b       2.2
2         3        c       3.3
3         4        d       4.4
4         5        e       5.5

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   coluna-1  5 non-null      int64
 1   coluna-2  5 non-null      object
 2   coluna-3  5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes

# 2. Começando com a biblioteca Numpy

## Importação da biblioteca

In [9]:
import numpy as np

## Criação de um array de 2 dimensões

In [10]:
dadosnp = np.array([[1,2,3],[4,5,6]])

In [11]:
dadosnp

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
dadosnp2 = np.arange(15, dtype=np.int64).reshape(3,5)

In [14]:
dadosnp2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Praticando com o pandas

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [18]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/books.csv', sep=',',on_bad_lines='skip')

In [19]:
df.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11123 entries, 0 to 11122
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   bookID              11123 non-null  int64
 1   title               11123 non-null  object
 2   authors             11123 non-null  object
 3   average_rating      11123 non-null  float64
 4   isbn                11123 non-null  object
 5   isbn13              11123 non-null  int64
 6   language_code       11123 non-null  object
 7     num_pages         11123 non-null  int64
 8   ratings_count       11123 non-null  int64
 9   text_reviews_count  11123 non-null  int64
 10  publication_date    11123 non-null  object
 11  publisher           11123 non-null  object
dtypes: float64(1), int64(5), object(6)
memory usage: 1.0+ MB

In [22]:
# Verificando linhas com amostras aleatórias

df.sample(5)

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
5327,19282,The Odyssey,Homer/Robert Fitzgerald/Seamus Heaney,3.76,1857150945,9781857150940,eng,509,48,3,10/8/1992,Everyman
2839,10559,The Three Musketeers,Alexandre Dumas/Barbara T. Cooper,4.07,1593081480,9781593081485,eng,761,1149,147,11/25/2004,Barnes Noble Classics
9790,39286,Hide-and-Seek with Angels: The Life of J.M. Ba...,Lisa Chaney,3.91,0099453231,9780099453239,eng,448,66,11,5/16/2006,Arrow
2674,9828,Rat Bastards: The Life and Times of South Bost...,"John ""Red"" Shea/Mark Wahlberg",3.51,0060837160,9780060837167,eng,304,34,3,3/14/2006,William Morrow
11110,45607,Las Crónicas de Narnia,C.S. Lewis/Margarita E. Valdes/Gemma Gallart/P...,4.26,0061199001,9780061199004,spa,816,186,11,11/7/2006,HarperCollins Espanol

In [23]:
# verifica se tem dados nulos
df.isnull().sum()

bookID                0
title                 0
authors               0
average_rating        0
isbn                  0
isbn13                0
language_code         0
  num_pages           0
ratings_count         0
text_reviews_count    0
publication_date      0
publisher             0
dtype: int64